import type { SfxrDefinition } from "jsfxr";

export type SfxKey =
  | "tick"
  | "pop"
  | "tap"
  | "whoosh"
  | "splash"
  | "splashChain"
  | "sparkle"
  | "sparkleChain"
  | "pour"
  | "shipmentLow"
  | "shipmentHigh"
  | "fanfareLow"
  | "fanfareMid"
  | "fanfareHigh"
  | "gameOver";

const BASE_SFX: SfxrDefinition = {
  oldParams: true,
  wave_type: 0,
  p_env_attack: 0,
  p_env_sustain: 0.05,
  p_env_punch: 0,
  p_env_decay: 0.08,
  p_base_freq: 0.5,
  p_freq_limit: 0,
  p_freq_ramp: 0,
  p_freq_dramp: 0,
  p_vib_strength: 0,
  p_vib_speed: 0,
  p_arp_mod: 0,
  p_arp_speed: 0,
  p_duty: 0.5,
  p_duty_ramp: 0,
  p_repeat_speed: 0,
  p_pha_offset: 0,
  p_pha_ramp: 0,
  p_lpf_freq: 1,
  p_lpf_ramp: 0,
  p_lpf_resonance: 0,
  p_hpf_freq: 0,
  p_hpf_ramp: 0,
  sound_vol: 0.25,
  sample_rate: 44100,
  sample_size: 8,
};

export const SFX_DEFINITIONS: Record<SfxKey, SfxrDefinition> = {
  tick: sfx({
    wave_type: 0,
    p_env_sustain: 0.015,
    p_env_decay: 0.035,
    p_base_freq: 0.66,
    p_freq_ramp: 0.08,
    p_duty: 0.18,
    p_hpf_freq: 0.22,
    sound_vol: 0.18,
  }),
  pop: sfx({
    wave_type: 1,
    p_env_sustain: 0.045,
    p_env_punch: 0.32,
    p_env_decay: 0.11,
    p_base_freq: 0.54,
    p_freq_ramp: 0.22,
    p_arp_mod: 0.18,
    p_arp_speed: 0.62,
    p_duty: 0.22,
    sound_vol: 0.2,
  }),
  tap: sfx({
    wave_type: 2,
    p_env_attack: 0.001,
    p_env_sustain: 0.003,
    p_env_punch: 0,
    p_env_decay: 0.014,
    p_base_freq: 0.42,
    p_freq_ramp: -0.008,
    p_duty: 0.56,
    p_lpf_freq: 0.28,
    p_hpf_freq: 0.08,
    sound_vol: 0.004,
  }),
  whoosh: sfx({
    wave_type: 3,
    p_env_attack: 0.01,
    p_env_sustain: 0.11,
    p_env_decay: 0.18,
    p_base_freq: 0.32,
    p_freq_ramp: -0.18,
    p_lpf_freq: 0.6,
    p_lpf_ramp: -0.16,
    p_hpf_freq: 0.08,
    sound_vol: 0.22,
  }),
  splash: sfx({
    wave_type: 2,
    p_env_attack: 0.004,
    p_env_sustain: 0.13,
    p_env_punch: 0.08,
    p_env_decay: 0.24,
    p_base_freq: 0.36,
    p_freq_ramp: -0.06,
    p_pha_offset: 0.08,
    p_pha_ramp: -0.04,
    p_lpf_freq: 0.5,
    p_lpf_resonance: 0.1,
    p_hpf_freq: 0,
    sound_vol: 0.17,
  }),
  splashChain: sfx({
    wave_type: 2,
    p_env_attack: 0.006,
    p_env_sustain: 0.1,
    p_env_punch: 0.12,
    p_env_decay: 0.2,
    p_base_freq: 0.44,
    p_freq_ramp: 0.04,
    p_arp_mod: 0.12,
    p_arp_speed: 0.68,
    p_lpf_freq: 0.56,
    sound_vol: 0.15,
  }),
  sparkle: sfx({
    wave_type: 2,
    p_env_sustain: 0.035,
    p_env_punch: 0.22,
    p_env_decay: 0.14,
    p_base_freq: 0.72,
    p_freq_ramp: 0.08,
    p_arp_mod: 0.42,
    p_arp_speed: 0.58,
    p_hpf_freq: 0.12,
    sound_vol: 0.18,
  }),
  sparkleChain: sfx({
    wave_type: 2,
    p_env_attack: 0.003,
    p_env_sustain: 0.07,
    p_env_punch: 0.16,
    p_env_decay: 0.18,
    p_base_freq: 0.58,
    p_freq_ramp: 0.05,
    p_arp_mod: 0.18,
    p_arp_speed: 0.58,
    p_lpf_freq: 0.64,
    p_hpf_freq: 0.05,
    sound_vol: 0.14,
  }),
  pour: sfx({
    wave_type: 3,
    p_env_attack: 0.02,
    p_env_sustain: 0.18,
    p_env_decay: 0.22,
    p_base_freq: 0.28,
    p_freq_ramp: -0.04,
    p_repeat_speed: 0.52,
    p_lpf_freq: 0.52,
    p_lpf_ramp: -0.05,
    p_hpf_freq: 0.06,
    sound_vol: 0.2,
  }),
  shipmentLow: sfx({
    wave_type: 0,
    p_env_sustain: 0.07,
    p_env_punch: 0.24,
    p_env_decay: 0.12,
    p_base_freq: 0.24,
    p_freq_ramp: -0.04,
    p_duty: 0.5,
    p_lpf_freq: 0.78,
    sound_vol: 0.2,
  }),
  shipmentHigh: sfx({
    wave_type: 1,
    p_env_sustain: 0.055,
    p_env_punch: 0.34,
    p_env_decay: 0.16,
    p_base_freq: 0.58,
    p_freq_ramp: 0.12,
    p_arp_mod: 0.26,
    p_arp_speed: 0.56,
    p_repeat_speed: 0.32,
    sound_vol: 0.2,
  }),
  fanfareLow: sfx({
    wave_type: 1,
    p_env_attack: 0.002,
    p_env_sustain: 0.08,
    p_env_punch: 0.28,
    p_env_decay: 0.12,
    p_base_freq: 0.42,
    p_freq_ramp: 0.05,
    p_arp_mod: 0.22,
    p_arp_speed: 0.52,
    p_lpf_freq: 0.9,
    sound_vol: 0.2,
  }),
  fanfareMid: sfx({
    wave_type: 1,
    p_env_attack: 0.001,
    p_env_sustain: 0.09,
    p_env_punch: 0.34,
    p_env_decay: 0.14,
    p_base_freq: 0.56,
    p_freq_ramp: 0.07,
    p_arp_mod: 0.3,
    p_arp_speed: 0.48,
    p_lpf_freq: 0.92,
    sound_vol: 0.22,
  }),
  fanfareHigh: sfx({
    wave_type: 2,
    p_env_attack: 0.001,
    p_env_sustain: 0.12,
    p_env_punch: 0.24,
    p_env_decay: 0.24,
    p_base_freq: 0.74,
    p_freq_ramp: 0.05,
    p_arp_mod: 0.42,
    p_arp_speed: 0.46,
    p_repeat_speed: 0.36,
    p_lpf_freq: 0.86,
    p_hpf_freq: 0.06,
    sound_vol: 0.23,
  }),
  gameOver: sfx({
    wave_type: 0,
    p_env_sustain: 0.11,
    p_env_punch: 0.08,
    p_env_decay: 0.2,
    p_base_freq: 0.22,
    p_freq_limit: 0.08,
    p_freq_ramp: -0.28,
    p_duty: 0.55,
    p_lpf_freq: 0.64,
    sound_vol: 0.24,
  }),
};

function sfx(overrides: Partial<SfxrDefinition>): SfxrDefinition {
  return { ...BASE_SFX, ...overrides };
}
