/** Effect keys generated by SFX Forge from `sfx.json`; the pack lives in `public/sfx`. */
export type SfxKey =
  | "move"
  | "rotate"
  | "soft_drop"
  | "land"
  | "squish"
  | "chain_chime"
  | "bottle_fill"
  | "bottle_burst"
  | "water_drop"
  | "water_clear"
  | "stage_up"
  | "clear_fanfare"
  | "game_over";

type ManifestSound = {
  key: string;
  files: string[];
  playbackRandom: { pitch: number; volume: number };
};

export type SfxPackEntry = {
  buffers: AudioBuffer[];
  /** Recommended random spread so repeated sounds do not feel mechanical. */
  pitchJitter: number;
  volumeJitter: number;
};

export type SfxPack = Map<SfxKey, SfxPackEntry>;

const SFX_BASE = `${import.meta.env.BASE_URL}sfx/`;

/** Fetches and decodes the whole pack. Missing or broken files are skipped so play never throws. */
export async function loadSfxPack(context: AudioContext, base = SFX_BASE): Promise<SfxPack> {
  const pack: SfxPack = new Map();
  const response = await fetch(`${base}sfx-manifest.json`);
  if (!response.ok) return pack;
  const manifest = (await response.json()) as { sounds?: ManifestSound[] };
  await Promise.all(
    (manifest.sounds ?? []).map(async (sound) => {
      const buffers = (
        await Promise.all(
          sound.files.map(async (file) => {
            try {
              const data = await (await fetch(`${base}${file}`)).arrayBuffer();
              return await context.decodeAudioData(data);
            } catch {
              return null;
            }
          }),
        )
      ).filter((buffer): buffer is AudioBuffer => buffer !== null);
      if (buffers.length === 0) return;
      pack.set(sound.key as SfxKey, { buffers, pitchJitter: sound.playbackRandom?.pitch ?? 0, volumeJitter: sound.playbackRandom?.volume ?? 0 });
    }),
  );
  return pack;
}
